// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnXU1RMJrc2WodsRxc0tj7DqFv_vNtL4I',
    appId: '1:339672413407:android:244a9cd9f67e036236e56a',
    messagingSenderId: '339672413407',
    projectId: 'ride-with-purpose',
    storageBucket: 'ride-with-purpose.firebasestorage.app',
    databaseURL: null,
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'YOUR_IOS_API_KEY',
  //   appId: 'YOUR_IOS_APP_ID',
  //   messagingSenderId: 'YOUR_IOS_MESSAGING_SENDER_ID',
  //   projectId: 'YOUR_IOS_PROJECT_ID',
  //   databaseURL: 'YOUR_IOS_DATABASE_URL',
  //   storageBucket: 'YOUR_IOS_STORAGE_BUCKET',
  //   androidClientId: 'YOUR_ANDROID_CLIENT_ID',
  //   iosClientId: 'YOUR_IOS_CLIENT_ID',
  //   iosBundleId: 'YOUR_IOS_BUNDLE_ID',
  // );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyX916fmuOLz5a6ZP78omaNylkNv67Gh4',
    appId: '1:339672413407:ios:0f3b54dad1b6082036e56a',
    messagingSenderId: '339672413407',
    projectId: 'ride-with-purpose',
    storageBucket: 'ride-with-purpose.firebasestorage.app',
    databaseURL: null, // Only add if Realtime Database is used

    // iOS-specific fields
    iosClientId:
        '339672413407-979h1qr6c6i62qaaalmq0omcugg3eue9.apps.googleusercontent.com',
    iosBundleId: 'com.craftech.rwpdriver',

    // Optional Android client for cross-platform auth
    androidClientId:
        '339672413407-6vuuh10i3f2to5gsi84cevu66ml0kjts.apps.googleusercontent.com',
  );
}
